import Head from "next/head";
import Link from "next/link";
import { Container, Row, Col, Card, Button } from "react-bootstrap";
import {
  faCircleUser,
  faUtensils,
  faBuilding,
  faMapLocationDot,
} from "@fortawesome/free-solid-svg-icons";

import stylesIntro from "../styles/Intro.module.scss";
import stylesTrusted from "../styles/Trusted.module.scss";
import stylesSystem from "../styles/System.module.scss";
import stylesCompare from "../styles/Compare.module.scss";
import stylesProcess from "../styles/Process.module.scss";
import stylesOptimize from "../styles/Optimize.module.scss";

import Hero from "../components/hero/Hero";
import Icon from "../components/icon/Icon";
import IconText from "../components/iconText/IconText";
import NumberText from "../components/numberText/NumberText";

import safeIcon from "../public/safe-secure.png";
import supportIcon from "../public/support.png";
import noOutdatedCodeIcon from "../public/no-outdated-code.png";
import fullyScaleableIcon from "../public/fully-scaleable.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>My eLane</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section id="home">
        <Hero
          title="The Time To Own Is Now."
          subTitle="Say goodbye to outdated, cookie-cutter ordering platforms with sky-high monthly fees and added commissions. We’re now offering you the opportunity to own the same tech used by the largest restaurant chains, along with our industry-leading experience, for a fraction of the cost it takes to develop. "
          btnText="Learn More"
          btnLink="/how-it-works/"
        />
        <section className={stylesIntro.intro}>
          <Container>
            <Row className="align-items-center">
              <Col lg="6">
                <iframe
                  width="100%"
                  height="450"
                  src="https://www.youtube.com/embed/T1mViqQhcvs"
                  title="YouTube video player"
                  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                ></iframe>
              </Col>
              <Col lg="6">
                <p>
                  Your digital presence is essential to operating a successful
                  and growing business. This means you need to have complete
                  confidence that your mobile experience runs as smoothly as
                  your business, and showcase your unique brand.
                  <br />
                  <br />
                  My eLane has been revolutionalizing online ordering for over
                  10 years. Our systems are the result of more than a decade of
                  extensive learning, building, and problem-solving with
                  big-name franchises ensuring that you have access to
                  everything you could need from a mobile ordering platform.
                  <br />
                  <br />
                  Fully customizable options allow you to own every aspect of
                  your brand, exactly the way you want it, from top to bottom at
                  a fraction of the cost of building your own platform.
                  <br />
                  <br />
                  We do everything we can to make sure your transition is as
                  stress-free as possible so your business never misses a beat
                  (or an order).
                  <br />
                  <br />
                  Why rent when you can buy an enterprise-level mobile ordering
                  infrastructure that effortlessly integrates everything your
                  business needs to meet the ever-changing demands of all your
                  customers?
                  <br />
                  <br />
                  Take advantage of our years of experience with a fast,
                  accurate, and user-friendly system that showcases your
                  distinctive business.
                </p>
                <p>
                  Ready for a change? <Link href="/contact/">Click here</Link>{" "}
                  to get started.
                </p>
              </Col>
            </Row>
          </Container>
        </section>
        {/* <section className={stylesTrusted.trusted}>
          <Container>
            <Row className="text-center">
              <Col lg="12">
                <h2>
                  Trusted by <span>Millions</span>
                </h2>
              </Col>
            </Row>
            <Row>
              <Col lg="3">
                <Icon
                  iconChoice={faCircleUser}
                  heading="1.9 million"
                  text="consumers"
                />
              </Col>
              <Col lg="3">
                <Icon
                  iconChoice={faUtensils}
                  heading="1000s"
                  text="of restaurants"
                />
              </Col>
              <Col lg="3">
                <Icon
                  iconChoice={faBuilding}
                  heading="10+"
                  text="years in business"
                />
              </Col>
              <Col lg="3">
                <Icon
                  iconChoice={faMapLocationDot}
                  heading="0"
                  text="breaches"
                />
              </Col>
            </Row>
          </Container>
        </section> */}
        <section className={stylesOptimize.optimize}>
          <Container>
            <Row>
              <Col lg="12">
                <h2 className="text-center">
                  <span>Optimize</span> Your Business
                </h2>
              </Col>
            </Row>
            <Row>
              <Col lg="6">
                <p>
                  Our all-in-one platform streamlines your business resulting in
                  more sales, better waste reduction, and increased profits
                </p>
                <p>
                  From the customer → to your POS →to your kitchen → and back.
                  My eLane seamlessly ensures nothing is missed even on the
                  busiest of days.
                </p>
                <p>
                  Patented and integrated GPS-triggered orders will even let you
                  know exactly when an order should be started and delivered so
                  everything is on time every time.
                </p>
              </Col>
              <Col lg="6">
                <p>All our Apps include options for:</p>
                <ul>
                  <li>Dine In</li>
                  <li>Take-Out</li>
                  <li>Drive-Thru</li>
                  <li>Curbside</li>
                  <li>Internal Delivery</li>
                  <li>DoorDash Drive</li>
                  <li>In Mall Delivery</li>
                </ul>
                <p>Never lose an opportunity to serve a new customer again.</p>
                <Link href="/contact">
                  <Button>Book a Demo</Button>
                </Link>
              </Col>
            </Row>
          </Container>
        </section>
        <section className={stylesSystem.system}>
          <Container>
            <Row>
              <Col lg="12">
                <h2 className="text-center">
                  What Our System <span>Offers</span>
                </h2>
                <IconText
                  icon={safeIcon}
                  iconAlt="safe and secure"
                  heading="Safe and Secure"
                  text={[
                    "When you utilize third-party apps, you don’t own the software, and they own your data. In the event of planned, or unplanned, downtime and security breaches, you have no control. Your online safety and security are extremely important to us, which is why with My eLane you have complete control over what information gets stored, where it gets stored, and only ",
                    <strong>you</strong>,
                    " have access.",
                    <br />,
                    <br />,
                    "Even with millions of users, we’re proud to say that in over a decade we have had ",
                    <strong>ZERO</strong>,
                    " security breaches and ",
                    <strong>ZERO</strong>,
                    " downtime.",
                  ]}
                />
                <IconText
                  icon={supportIcon}
                  iconAlt="Total Support"
                  heading="Total Support"
                  text={[
                    " We will work with your team from start to finish to make sure that there are no gaps in your service. We set it up, test it, and when everything is perfect- and you’re happy- we publish it. No long wait times and no emails or calls left unanswered.",
                    <br />,
                    <br />,
                    "When you have questions, we have answers.",
                    <br />,
                    <br />,
                    "Our team knows our software inside and out which makes us the ultimate no-hassle choice for adding features, but you always have the option of hiring your own team to work on it for you- When you own, you have choices.",
                  ]}
                />
                <IconText
                  icon={noOutdatedCodeIcon}
                  iconAlt="No Outdated Code"
                  heading="No Outdated Code"
                  text={[
                    "Decades of research and development have gone into My eLane software. We pride ourselves on staying current and making sure that our systems can handle everything your business throws at you.",
                    <br />,
                    <br />,
                    "This means that our code is not only modern but perfectly suited to manage thousands of orders a day.",
                  ]}
                />
                <IconText
                  icon={fullyScaleableIcon}
                  iconAlt="Fully Scaleable"
                  heading="Fully Scaleable"
                  text="The problem with many third-party and rentable apps is that you have to re-evaluate
                  your systems as you grow. We’ve accounted for all of that. Our software is designed to grow with you so that you never have to worry about another ordering system ever again. Whether you’re just starting, or have thousands of locations, our software will be there for you every step of the way."
                />
              </Col>
            </Row>
            <Row>
              <Col className="text-center p-t-80" lg="12">
                <h2>
                  Take <span>Control</span> Of Your Business
                </h2>
                <Link href="/contact">
                  <Button>Get In Touch Today</Button>
                </Link>
              </Col>
            </Row>
          </Container>
        </section>
        <section className={stylesCompare.compare}>
          <Container>
            <Row className="text-center">
              <Col lg="12">
                <h2>
                  How Do We <span>Compare?</span>
                </h2>
              </Col>
            </Row>
            <Row>
              <Col lg="6">
                <Card>
                  <h4>Them</h4>
                  <ul>
                    <li>High monthly fees or sky-high development prices</li>
                    <li>Development takes years for high-level systems</li>
                    <li>Added commission on top of fees</li>
                    <li>Limited customizability</li>
                    <li>Minimal personal branding</li>
                    <li>Slow, outdated</li>
                    <li>Third-party hosting (no control!)</li>
                    <li>Potential for fraud is high when data is leaked</li>
                    <li>Few direct integrations (middleware= extra fees)</li>
                    <li>Confusing promotion integrations</li>
                    <li>Long wait times for custom features</li>
                    <li>Someone else owns your tech (unpredictable)</li>
                    <li>You don’t truly own anything</li>
                  </ul>
                </Card>
              </Col>
              <Col lg="6">
                <Card>
                  <h4>
                    <span>My eLane</span>
                  </h4>
                  <ul>
                    <li>No monthly fees (you own it!)</li>
                    <li>No commissions</li>
                    <li>Fully customizable</li>
                    <li>Show off your personalized brand</li>
                    <li>Modern, high tech code</li>
                    <li>GPS triggered arrival with ETA</li>
                    <li>No Third-Party</li>
                    <li>
                      Full administration backend panel to access all features
                    </li>
                    <li>
                      Integrates into your payment provider and POS system
                    </li>
                    <li>
                      3D secure for payments and integrated Apple and Google Pay
                    </li>
                    <li>
                      Allow your customers to pay however they choose, including
                      Interac
                    </li>
                    <li>
                      DoorDash Drive integration or custom delivery methods
                    </li>
                    <li>Highest quality promotions/coupon engine</li>
                    <li>
                      Use our in-house development team, or hire your own to do
                      custom development
                    </li>
                    <li>Comprehensive support</li>
                    <li>You own every aspect of your tech</li>
                    <li>And more!</li>
                  </ul>
                </Card>
              </Col>
            </Row>
            <Row>
              <Col className="text-center p-t-40" lg="12">
                <Link href="/contact">
                  <Button>Request More Information</Button>
                </Link>
              </Col>
            </Row>
          </Container>
        </section>
        <section className={stylesProcess.process}>
          <Container>
            <Row>
              <Col lg="12">
                <h2>
                  Our <span>Powerful</span> 5 Step Process
                </h2>
                <p>
                  In 5 simple steps, My eLane provides you with a no hassle,
                  business-ready ordering system.
                </p>
                <p>Once you sign up we:</p>
              </Col>
            </Row>
            <NumberText
              number="1"
              text="Discuss any custom design and function features you want to be implemented in order to fulfill your business’s needs."
            />
            <NumberText
              number="2"
              text="Your POS and payment providers are integrated into your system."
            />
            <NumberText
              number="3"
              text="Our specialists, engineers, and cloud consultants advise and set up your new cloud environment as well as the software that will make day-to-day operations effortless."
            />
            <NumberText
              number="4"
              text="We review your unique system from top to bottom in-house, then work with your team to ensure everything is working seamlessly in your test stores."
            />
            <NumberText
              number="5"
              text="When you’re happy- we’re happy! Only then do we publish the apps and systems to make sure that you get everything you need."
            />
            <p className={stylesProcess.closing}>
              Designing, coding, and implementing your own enterprise quality
              system takes years, and millions of dollars to create, even with
              the best developers. My eLane has made it our mission to provide
              all businesses, large and small, with a high-quality, lower-cost
              option to help their companies thrive.
            </p>
            <Link href="/contact">
              <Button>Get a Quote</Button>
            </Link>
          </Container>
        </section>
      </section>
    </>
  );
}
