import Head from "next/head";
import { Container, Row, Col, Card } from "react-bootstrap";
import {
  faCircleUser,
  faUtensils,
  faBuilding,
  faMapLocationDot,
} from "@fortawesome/free-solid-svg-icons";

import stylesIntro from "../styles/Intro.module.scss";
import stylesTrusted from "../styles/Trusted.module.scss";
import stylesSystem from "../styles/System.module.scss";
import stylesCompare from "../styles/Compare.module.scss";
import stylesProcess from "../styles/Process.module.scss";

import Hero from "../components/hero/Hero";
import Icon from "../components/icon/Icon";
import IconText from "../components/iconText/IconText";
import NumberText from "../components/numberText/NumberText";

import safeIcon from "../public/safe-secure.png";
import supportIcon from "../public/support.png";
import noOutdatedCodeIcon from "../public/no-outdated-code.png";
import fullyScaleableIcon from "../public/fully-scaleable.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>My eLane</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section id="home">
        <Hero
          title="The Time To Own Is Now."
          subTitle="Say goodbye to outdated, cookie-cutter ordering platforms with sky-high monthly fees and added commissions. Expand your restaurant’s reach and increase your sales with My eLane’s turnkey online ordering system today."
          btnText="Learn More"
          btnLink="/how-it-works/"
        />
        <section className={stylesIntro.intro}>
          <Container>
            <Row className="align-items-center">
              <Col lg="6">
                <h2>Video</h2>
              </Col>
              <Col lg="6">
                <p>
                  Your digital presence is essential to operating a successful
                  and growing business. This means you need to have complete
                  confidence that your apps run as smoothly as your business,
                  and showcase your unique brand.
                  <br />
                  <br />
                  My eLane has been revolutionalizing online ordering for over
                  10 years. Our systems are the result of more than a decade of
                  learning, building, and problem-solving to ensure that you
                  have access to everything you could need from a mobile
                  ordering platform.
                  <br />
                  <br />
                  Fully customizable options allow you to own every aspect of
                  your brand, exactly the way you want it, from top to bottom at
                  a fraction of the cost of building your own platform.
                  <br />
                  <br />
                  We do everything we can to make sure your transition is as
                  stress-free as possible so your business never misses a beat
                  (or an order).
                  <br />
                  <br />
                  Why rent when you can buy an enterprise-level mobile ordering
                  infrastructure that effortlessly integrates everything your
                  business needs to meet the ever-changing demands of all your
                  customers?
                  <br />
                  <br />
                  Take advantage of the online ordering boom with a fast,
                  accurate, and user-friendly system that showcases your
                  distinctive business.
                </p>
              </Col>
            </Row>
          </Container>
        </section>
        <section className={stylesTrusted.trusted}>
          <Container>
            <Row className="text-center">
              <Col lg="12">
                <h2>
                  Trusted by <span>Millions</span>
                </h2>
              </Col>
            </Row>
            <Row>
              <Col lg="3">
                <Icon
                  iconChoice={faCircleUser}
                  heading="1.9 million"
                  text="consumers"
                />
              </Col>
              <Col lg="3">
                <Icon
                  iconChoice={faUtensils}
                  heading="1000s"
                  text="of restaurants"
                />
              </Col>
              <Col lg="3">
                <Icon
                  iconChoice={faBuilding}
                  heading="10+"
                  text="years in business"
                />
              </Col>
              <Col lg="3">
                <Icon
                  iconChoice={faMapLocationDot}
                  heading="0"
                  text="breaches"
                />
              </Col>
            </Row>
          </Container>
        </section>
        <section className={stylesSystem.system}>
          <Container>
            <Row>
              <Col lg="12">
                <h2 className="text-center">
                  What Our System <span>Offers</span>
                </h2>
                <IconText
                  icon={safeIcon}
                  iconAlt="safe and secure"
                  heading="Safe and Secure"
                  text="When you utilize third-party apps, you don’t own the software. They can store information from you, as well as your customers. In the event of a security breach, all of that information can be accessed. Your online safety and security are extremely important to us, which is why with My eLane you have complete control over what information gets stored, as well as integrated security to prevent breaches in the first place. Even with millions of users, we’re proud to say that in over a decade we have had ZERO security breaches."
                />
                <IconText
                  icon={supportIcon}
                  iconAlt="Total Support"
                  heading="Total Support"
                  text="We can work with your team from start to finish to make sure that there are no gaps in your
                  service. We set it up, test it, and when everything is perfect- and you’re happy- we publish it. No
                  long wait times and no emails or calls left unanswered. When you have questions, we have answers."
                />
                <IconText
                  icon={noOutdatedCodeIcon}
                  iconAlt="No Outdated Code"
                  heading="No Outdated Code"
                  text="Decades of research and development have gone into My eLane software. We pride
                  ourselves on staying current and making sure that our systems can handle everything your
                  business throws at you. This means that our codes are not only modern but perfectly suited to manage thousands of orders a day."
                />
                <IconText
                  icon={fullyScaleableIcon}
                  iconAlt="Fully Scaleable"
                  heading="Fully Scaleable"
                  text="The problem with many third-party and rentable apps is that you have to re-evaluate
                  your systems as you grow. We’ve accounted for all of that. Our software is designed to grow with you so that you never have to worry about another ordering system ever again. Whether you’re just starting, or have thousands of locations, our software will be there for you every step of the way."
                />
              </Col>
            </Row>
          </Container>
        </section>
        <section className={stylesCompare.compare}>
          <Container>
            <Row className="text-center">
              <Col lg="12">
                <h2>
                  How Do We <span>Compare?</span>
                </h2>
              </Col>
            </Row>
            <Row>
              <Col lg="6">
                <Card>
                  <h4>Them</h4>
                  <ul>
                    <li>High monthly fees</li>
                    <li>Added commission on top of fees</li>
                    <li>Limited customizability</li>
                    <li>Minimal personal branding</li>
                    <li>Slow, outdated</li>
                    <li>Third-party hosting (no control)</li>
                    <li>Potential for fraud is high when data is leaked</li>
                    <li>
                      Have to use an outside delivery service like DoorDash
                    </li>
                    <li>Very few integrations</li>
                    <li>Some limit payment methods</li>
                    <li>Confusing promotion integrations</li>
                    <li>Long wait times if you’re designing your own</li>
                    <li>Someone else owns your tech (unpredictable)</li>
                    <li>You don’t truely own anything</li>
                  </ul>
                </Card>
              </Col>
              <Col lg="6">
                <Card>
                  <h4>
                    <span>My eLane</span>
                  </h4>
                  <ul>
                    <li>No monthly fees (you own it!)</li>
                    <li>No commissions</li>
                    <li>Fully customizable</li>
                    <li>Show off your personalized brand</li>
                    <li>Modern, high tech code</li>
                    <li>GPS triggered arrival with ETA</li>
                    <li>No Third-Party</li>
                    <li>
                      Integrated 3DS 2.0, Kount proprietary fraud tool for
                      account takeover
                    </li>
                    <li>
                      Allow your customers to pay however they choose, including
                      Interac
                    </li>
                    <li>Choose your own delivery method</li>
                    <li>
                      Highest quality promotions/coupon engine with available
                      promo blocking
                    </li>
                    <li>Use our in-house development team, or hire your own</li>
                    <li>Comprehensive support</li>
                    <li>You own every aspect of your tech</li>
                    <li>And more!</li>
                  </ul>
                </Card>
              </Col>
            </Row>
          </Container>
        </section>
        <section className={stylesProcess.process}>
          <Container>
            <Row>
              <Col lg="12">
                <h2>
                  Our <span>Powerful</span> 5 Step Process
                </h2>
                <p>
                  In 5 simple steps, My eLane provides you with a no hassle,
                  business-ready ordering system.
                </p>
              </Col>
            </Row>
            <NumberText
              number="1"
              text="Discuss any custom design and function features you want implemented in order to fulfill your business’s needs."
            />
            <NumberText
              number="2"
              text="Your POS and payment providers are integrated into your system."
            />
            <NumberText
              number="3"
              text="Our specialists, engineers, and cloud consultants advise and set up your new cloud environment as well as the software that will make day-to-day operations effortless."
            />
            <NumberText
              number="4"
              text="We review your unique system from top to bottom in-house, then work with your team to ensure everything is working seamlessly in your test stores."
            />
            <NumberText
              number="5"
              text="When you’re happy- we’re happy! Only then do we publish the apps and systems to make sure that you get everything you need."
            />
            <p className={stylesProcess.closing}>
              Designing, coding, and implementing your own enterprise quality
              system takes years, and millions of dollars to create. My eLane
              has made it our mission to provide all businesses, large and
              small, with a high quality, lower cost option to help their
              companies thrive.
            </p>
          </Container>
        </section>
      </section>
    </>
  );
}
